version: '3.7'

networks:
  agent_network:
    driver: overlay
    attachable: true

services:
  portainer-agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - traefik
      - agent-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.portainer.portainer-data == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
        - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
