version: '3.7'

networks:
  traefik:
    external: true
    name: ${TRAEFIK_PUBLIC_NETWORK}

volumes:
  portainer-data:

services:
  portainer:
    image: portainer/portainer
    volumes:
      - portainer-data:/data
    networks:
      - traefik
