version: '3.7'

networks:
  agent-network:
    attachable: true

  traefik:
    external: true
    name: ${TRAEFIK_PUBLIC_NETWORK}

volumes:
  portainer-data:

services:
  portainer:
    image: portainer/portainer
    networks:
      - agent-network
      - traefik
