version: '3.7'

networks:
  traefik:
    external: true
    name: ${TRAEFIK_PUBLIC_NETWORK}
  pg_network:
    name: ${POSTGRES_NETWORK}
    attachable: true

volumes:
  postgres-data:

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - pg_network
    command: postgres -N 500

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - traefik
      - pg_network
