version: '3.7'

networks:
  net:
    # driver: overlay
    attachable: true

  traefik:
    external: true
    name: ${TRAEFIK_PUBLIC_NETWORK}

volumes:
  db-data:
    driver: local

services:
  app:
    image: swarmpit/swarmpit:latest
    # image: swarmpit/swarmpit:1.6
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
