version: '3.7'

volumes:
  letsencrypt-certificates:

networks:
  traefik:
    name: ${TRAEFIK_PUBLIC_NETWORK}

services:
  traefik:
    image: traefik:v2.0
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - TZ=Europe/Zurich
    ports:
      # HTTP & HTTPS
      - '80:80'
      - '443:443'
      # Other services
      - '${SSH_PORT}:22'
      - '${PG_PORT}:5432'
      - target: 27017
        published: ${MONGO_PORT}
        protocol: tcp
        mode: host
    networks:
      - default
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "letsencrypt-certificates:/letsencrypt"
