version: '3.7'

services:
  traefik:
    command:
      - '--global.checkNewVersion=false'
      - '--global.sendAnonymousUsage=false'
      # DOCKER (Dynamic config)
      - '--providers.docker'
      - '--providers.docker.watch=true'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=${TRAEFIK_PUBLIC_NETWORK}'
      - '--providers.docker.swarmMode=true'
      # activate WEBMIN
      - '--api.dashboard'
      # Listen to incoming HTTP requests (80)
      - '--entryPoints.web.address=:80'
      # Listen to HTTPS (443)
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.cloudflare.acme.email=${LETSENCRYPT_EMAIL}'
      - '--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge=true'
      - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
      # Listen to other services
      - '--entryPoints.ssh.address=:22'
      - '--entryPoints.pg.address=:5432'
      - '--entryPoints.mongo-dev.address=:${MONGO_PORT_DEV}'
      - '--entryPoints.mongo-qa.address=:${MONGO_PORT_QA}'
      # DEBUG
      - '--log.level=INFO'

    deploy:
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
        - "traefik.docker.lbswarm=true"
        # webmin protected by BasicAuth
        - "traefik.http.middlewares.ask-basic-auth.basicauth.users=${BASIC_AUTH}"
        - "traefik.http.routers.traefik-webmin.rule=Host(`${TRAEFIK_CNAME}`)"
        - "traefik.http.routers.traefik-webmin.entrypoints=websecure"
        - "traefik.http.routers.traefik-webmin.tls.certresolver=cloudflare"
        - "traefik.http.routers.traefik-webmin.service=api@internal"
        - "traefik.http.routers.traefik-webmin.middlewares=ask-basic-auth"
        - "traefik.http.services.traefik-webmin.loadbalancer.server.port=8080"
        # proxy unit requests
        - "traefik.http.middlewares.unit-redirect.redirectregex.regex=^https?//([^/]*)/(.*)"
        - "traefik.http.middlewares.unit-redirect.redirectregex.replacement=http//$${1}/$${2}"
        - "traefik.http.routers.unit-proxy.rule=hostregexp(`api-eu.pusher.com`, `logs7.papertrailapp.com`, `bitbucket.org`, `sentry.io`, `mailgun.org`)"
        - "traefik.http.routers.unit-proxy.entrypoints=web"
        - "traefik.http.routers.unit-proxy.priority=100"
        - "traefik.http.routers.unit-proxy.middlewares=unit-redirect"
        # global redirect to https
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.redirects.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.redirects.entrypoints=web"
        - "traefik.http.routers.redirects.priority=10"
        - "traefik.http.routers.redirects.middlewares=redirect-to-https"
